#!/bin/sh 
cat << "EOF"
                                                              
                                                       ____   
                    ,---,               .---.        ,'  , `. 
                  .'  .' `\            /. ./|     ,-+-,.' _ | 
                ,---.'     \       .--'.  ' ;  ,-+-. ;   , || 
                |   |  .`\  |     /__./ \ : | ,--.'|'   |  ;| 
                :   : |  '  | .--'.  '   \' .|   |  ,', |  ': 
                |   ' '  ;  :/___/ \ |    ' '|   | /  | |  || 
                '   | ;  .  |;   \  \;      :'   | :  | :  |, 
                |   | :  |  ' \   ;  `      |;   . |  ; |--'  
                '   : | /  ;   .   \    .\  ;|   : |  | ,     
                |   | '` ,/     \   \   ' \ ||   : '  |/      
                ;   :  .'        :   '  |--" ;   | |`-'       
                |   ,.'           \   \ ;    |   ;/           
                '---'              '---"     '---'           

                         Dwm Auto Install Script
EOF
sleep 2
folders="$HOME/sourcecode $HOME/.local/bin"
echo "checking and installing needed packages"
packagemanagers="pacman emerge xbps-install"
roots="sudo doas"
for root in $roots; do
  if command -v "$root" > /dev/null 2>&1; then
    case "$root" in
      sudo) roots="sudo" ;;
      doas) roots="doas" ;;
    esac
    break
  fi
done

for packagemanager in $packagemanagers; do
  if command -v "$packagemanager" > /dev/null 2>&1;then
    case "$packagemanager" in
      pacman) $roots pacman -S libxft ttf-sourcecodepro-nerd meson acpi uthash noto-fonts-emoji git feh picom imagemagick python-pipx openssh ttf-iosevka-nerd yt-dlp ranger zip ;;
      emerge) $roots emerge --ask media-fonts/noto-emoji acpi dev-util/meson dev-libs/uthash dev-vcs/git media-gfx/imagemagick media-gfx/feh x11-misc/picom net-misc/openssh net-misc/yt-dlp ranger app-arch/zip ;;
      xbps-install) $roots xbps-install -S xrdb git base-devel feh picom ImageMagick noto-fonts-emoji font-iosevka python3-pip curl libXinerama-devel fontconfig-devel libXft-devel harfbuzz-devel yt-dlp ytcc ranger zip ;;
    esac
    break
  fi
done

sleep 1
echo "Checking folders and creating it"

for folder in $folders; do
  if [ ! -d $folder ]; then
    mkdir -p $HOME/sourcecode
    mkdir -p $HOME/.local/bin
    break
  fi
done

echo "Clone the repos"
sleep 1
#clone the repos
git clone https://github.com/yshui/picom $HOME/picom && cd picom && meson setup --buildtype=release build && sudo ninja -C build install && cd ..
git clone https://github.com/charlesmenez/Wallpapers $HOME/Wallpapers
git clone https://github.com/guillaumeboehm/wal-telegram $HOME/sourcecode/wal-telegram
$roots make -C $HOME/sourcecode/wal-telegram/ install
git clone https://github.com/charlesmenez/shellscript $HOME/sourcecode/shellscript
$roots ln -s ~/sourcecode/shellscript/bookmarks /usr/local/bin/
ln -s ~/sourcecode/shellscript/share/bookmarks ~/
$roots ln -s ~/sourcecode/shellscript/dmenu-emoji /usr/local/bin/
ln -s ~/sourcecode/shellscript/share/emoji ~/
git clone https://github.com/charlesmenez/dwm $HOME/sourcecode/dwm
git clone https://github.com/charlesmenez/dwmblocks $HOME/sourcecode/dwmblocks
git clone https://github.com/charlesmenez/dmenu $HOME/sourcecode/dmenu
git clone https://github.com/charlesmenez/st $HOME/sourcecode/st
$roots cp $HOME/sourcecode/dwmblocks/scripts/* /usr/local/bin/

#pull the script and making it executable
$roots curl -L https://raw.githubusercontent.com/charlesmenez/shellscript/main/dwm-colors -o /usr/local/bin/dwm-colors
$roots curl -L https://raw.githubusercontent.com/charlesmenez/shellscript/main/sysact -o /usr/local/bin/sysact
$roots curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/yt-dlp/yt-dlp.conf -o /etc/yt-dlp.conf
curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/picom/picom.conf -o ~/.config/picom.conf
$roots chmod +x /usr/local/bin/sysact
$roots chmod +x /usr/local/bin/dwm-colors
sleep 1
echo "checking if pywal it's installed, if not i'm install for you"
sleep 1
#check if pywal is installed
if ! pip3 show pywal > /dev/null; then
  pip install pywal --user
else
  echo "Congrats you have pywal, but make sure if it's in your PATH"
fi

$roots ln -s ~/.local/bin/wal /usr/local/bin/

if [ ! -f "$HOME/.Xresources $HOME/.xinitrc" ]; then
  touch $HOME/.Xresources
  curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/xinitrc -o $HOME/.xinitrc
elif [ -f "$HOME/.Xresources $HOME/.xinitrc"]; then
  nv $HOME/.xinitrc $HOME/.xinitrcbkp
  mv $HOME/.Xresources $HOME/.Xresourcesbkp
  touch $HOME/.Xresources
  curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/xinitrc -o $HOME/.xinitrc
fi
wal -i $HOME/Wallpapers/minimal.png
cat ~/.cache/wal/colors.Xresources >> $HOME/.Xresources

$roots make -C $HOME/sourcecode/st/ install
$roots make -C $HOME/sourcecode/dwmblocks/ install
$roots make -C $HOME/sourcecode/dwm/ install
$roots make -C $HOME/sourcecode/dmenu/ install

