#!/bin/sh 

if [ ! -d "$HOME/sourcecode" ]; then
  mkdir -p "$HOME/sourcecode"
  mkdir -p "$HOME/Wallpapers"
  mkdir -p "$HOME/.local/bin"
  git clone https://github.com/charlesmenez/dwm $HOME/sourcecode/dwm
  git clone https://github.com/charlesmenez/dwmblocks $HOME/sourcecode/dwmblocks
  git clone https://github.com/charlesmenez/dmenu $HOME/sourcecode/dmenu
  git clone https://github.com/charlesmenez/st $HOME/sourcecode/st
fi

cp $HOME/sourcecode/dwmblocks/scripts/* $HOME/.local/bin/
curl -L https://raw.githubusercontent.com/charlesmenez/shellscript/main/dwm-colors -o $HOME/.local/bin/dwm-colors
chmod +x $HOME/.local/bin/dwm-colors
pip install pywal --user
echo "export PATH='$PATH:~/.local/bin'" >> $HOME/.bash_profile
if [ ! -f "$HOME/.Xresources" ]; then
  touch $HOME/.Xresources
fi


if [ -f "$HOME/.xinitrc" ]; then
  mv $HOME/.xinitrc .xinitrcbkp
fi
curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/xinitrc -o $HOME/.xinitrc

folders="$HOME/sourcecode/dwm $HOME/sourcecode/dmenu $HOME/sourcecode/st $HOME/sourcecode/dwmblocks"
for folder in $folders; do
  cd "$folders"
  doas make install
done
