#!/bin/sh 
cat << "EOF"
                                                              
                                                       ____   
                    ,---,               .---.        ,'  , `. 
                  .'  .' `\            /. ./|     ,-+-,.' _ | 
                ,---.'     \       .--'.  ' ;  ,-+-. ;   , || 
                |   |  .`\  |     /__./ \ : | ,--.'|'   |  ;| 
                :   : |  '  | .--'.  '   \' .|   |  ,', |  ': 
                |   ' '  ;  :/___/ \ |    ' '|   | /  | |  || 
                '   | ;  .  |;   \  \;      :'   | :  | :  |, 
                |   | :  |  ' \   ;  `      |;   . |  ; |--'  
                '   : | /  ;   .   \    .\  ;|   : |  | ,     
                |   | '` ,/     \   \   ' \ ||   : '  |/      
                ;   :  .'        :   '  |--" ;   | |`-'       
                |   ,.'           \   \ ;    |   ;/           
                '---'              '---"     '---'           

                         Dwm Auto Install Script
EOF
sleep 2
folders="$HOME/sourcecode $HOME/Wallpapers $HOME/.local/bin"
echo "checking and installing needed packages"
packagemanagers="pacman emerge xbps-install"

for packagemanager in $packagemanagers; do
  if command -v "$packagemanager" > /dev/null 2>&1;then
    case "$packagemanager" in
      pacman) sudo pacman -S noto-fonts-emoji git feh picom imagemagick python-pip openssh ttf-iosevka-nerd opendoas ;;
      emerge) doas emerge --ask media-fonts/noto-emoji dev-vcs/git media-gfx/imagemagick media-gfx/feh x11-misc/picom net-misc/openssh ;;
      xbps-install) sudo xbps-install -S git base-devel feh picom ImageMagick noto-fonts-emoji font-iosevka python-pip ;;
    esac
    break
  fi
done

sudo echo "permit persist :wheel" > /etc/doas.conf

#distro=$(uname -a | awk '{print $2}')
#if [ "$distro" == "archlinux" ]; then
#doas pacman -S noto-fonts-emoji git feh picom imagemagick python-pip openssh ttf-iosevka-nerd
#elif [ "$distro" == "gentoo" ]; then
#doas emerge --ask media-fonts/noto-emoji app-admin/doas dev-vcs/git media-gfx/imagemagick media-gfx/feh x11-misc/picom net-misc/openssh 
#elif [ "$distro" == "voidlinux" ]; then
#doas emerge --ask media-fonts/noto-emoji app-admin/doas dev-vcs/git media-gfx/imagemagick media-gfx/feh x11-misc/picom net-misc/openssh 
#else
#  echo "your distro it isn't compatible"
#  sleep 1
#  exit 1
#fi
  

sleep 1
echo "Checking folders and creating it"

for folder in $folders; do
  if [ ! -d $folder ]; then
    mkdir -p $HOME/sourcecode
    mkdir -p $HOME/Wallpapers
    mkdir -p $HOME/.local/bin
    break
  fi
done

echo "Clone the repos"
sleep 1
#clone the repos
git clone https://github.com/charlesmenez/dwm $HOME/sourcecode/dwm
git clone https://github.com/charlesmenez/dwmblocks $HOME/sourcecode/dwmblocks
git clone https://github.com/charlesmenez/dmenu $HOME/sourcecode/dmenu
git clone https://github.com/charlesmenez/st $HOME/sourcecode/st
doas cp $HOME/sourcecode/dwmblocks/scripts/* /usr/local/bin/
#pull the script and making it executable
doas curl -L https://raw.githubusercontent.com/charlesmenez/shellscript/main/dwm-colors -o /usr/local/bin/dwm-colors
doas chmod +x /usr/local/bin/dwm-colors
#downloading some wallpaper
curl -L https://raw.githubusercontent.com/charlesmenez/Wallpapers/main/dwm.png -o $HOME/Wallpapers/dwm.png
sleep 1
echo "checking if pywal it's installed, if not i'm install for you"
sleep 1
#check if pywal is installed
if ! pip3 show pywal > /dev/null; then
  pip install pywal --user
else
  echo "Congrats you have pywal, but make sure if it's in your PATH"
fi

doas ln -s ~/.local/bin/wal /usr/local/bin/

if [ ! -f "$HOME/.Xresources $HOME/.xinitrc" ]; then
  touch $HOME/.Xresources
  curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/xinitrc -o $HOME/.xinitrc
elif [ -f "$HOME/.Xresources $HOME/.xinitrc"]; then
  nv $HOME/.xinitrc $HOME/.xinitrcbkp
  mv $HOME/.Xresources $HOME/.Xresourcesbkp
  touch $HOME/.Xresources
  curl -L https://raw.githubusercontent.com/charlesmenez/dotfiles/main/xinitrc -o $HOME/.xinitrc
fi
wal -i $HOME/Wallpapers/dwm.png
cat ~/.cache/wal/colors.Xresources >> $HOME/.Xresources

doas make -C $HOME/sourcecode/st/ install
doas make -C $HOME/sourcecode/dwmblocks/ install
doas make -C $HOME/sourcecode/dwm/ install
doas make -C $HOME/sourcecode/dmenu/ install

