#!/bin/bash
#set -e
#DMENU_CMD="dmenu -i"
#THEME="forest
#gentoo-green
#space
#abstract
#church
#modern
#ocean
#concrete
#"
#CHOICE=$(printf "$THEME" | $DMENU_CMD -p "Select a theme:")
CHOICE=$(ls -1 ~/.config/awesome/wallpapers/ | dmenu -i -l 10)

case $CHOICE in
  $CHOICE) wal -i ~/.config/awesome/wallpapers/$CHOICE && convert ~/.config/awesome/wallpapers/$CHOICE* ~/custom.jpg && awesome-client 'awesome.restart()' ;;

esac

