#!/bin/bash
set -e
DMENU_CMD="dmenu -nb black -nf white -sb white -sf black -fn hack:size=10 -i"
THEME="space
blossoming-almond-tree
arco
forest
abstract
gentoo-green
"
BACKEND="colorz
wal
haishoku
colorthief"

CHOICE=$(printf "$THEME" | $DMENU_CMD -p "Select a theme")
BACKENDCHOICE=$(printf "$BACKEND" | $DMENU_CMD -p "Select a backend")
SWALLOW=

case $CHOICE in
  $CHOICE) wal -i ~/.config/awesome/wallpapers/$CHOICE* --backend $BACKENDCHOICE && convert ~/.config/awesome/wallpapers/$CHOICE* ~/custom.jpg && feh --bg-scale ~/custom.jpg && alacritty-xresources-color ;;

esac


if [ -z "$CHOICE" ]; then
  exit 1
else
  echo 'awesome.restart()' | awesome-client
fi
