#!/bin/bash

# Define the options
options=("gaming" "web" "compiling")

# Prompt the user to select an option using dmenu
selected_option=$(printf '%s\n' "${options[@]}" | dmenu -p "select a profile")

# Handle the selected option
case $selected_option in
    "gaming")
        doas cpupower frequency-set -u 3.0ghz;;
    "web")
        doas cpupower frequency-set -u 2.4ghz;;
    "compiling")
        doas cpupower frequency-set -u 4.3ghz;;
esac

