#!/bin/sh

#set dmenu theme
DMENU_CMD="dmenu -fn monospace:size=9 -nb black -sb white -sf black"
#input a movie variable
search=$(echo | $DMENU_CMD -p "Search a movie")

#if statement to see if search variable is NULL
if [ -z "$search" ]; then
  exit 0
fi

# change the search variable spaces with +
query=$(printf "$search" | tr ' ' '+' )
# search the movie on 1337x and send output to dmenu prompt
movie=$(curl -s https://1337x.to/search/$query/1/ | grep -Eo "torrent\/[0-9]{1,9}\/[a-zA-Z0-9?%-]*/" | $DMENU_CMD -i -l 20 -p 'which movie?')
magnetlink=$(curl -s https://1337x.to/$movie | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)

#if statement to see if magnetlink variable is NULL
if [ -z "$magnetlink"]; then
  exit 0
fi

alacritty -e peerflix $magnetlink -l -k --path ~/MassStorage/Movies
