#!/bin/sh

# A dmenu wrapper script for system functions.
set -e
dmenu="dmenu -i"
cmds="🚪leave
🔃reboot
🖥shutdown"

choice=$(printf "$cmds" | $dmenu -p "select a action:")
SWALLOW=
if [ -z "$choice" ]; then
  exit 0
fi
case $choice in
   🔃reboot) doas reboot ;;
   🖥shutdown) doas shutdown -h now ;;
   🚪leave) pkill X ;;
esac

