#!/bin/bash
set -e
CHOICES="LukeSmith
MentalOutlaw
FabioAkita
DistroTube
LinusTechTips
PeperaioHardware
EiNerd
Canal90
DioLinux
CovildeJack
ShortCircuit
ResumindoFilmes
ThePrimeagen"

CHOICE=$(printf "$CHOICES" | dmenu -i -l 30 -p "Select a Channel:")
SWALLOW=

case $CHOICE in
  LukeSmith) ytfzf -D -c youtube-channel https://youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA ;;
  MentalOutlaw) ytfzf -D -c youtube-channel https://youtube.com/channel/UC7YOGHUfC1Tb6E4pudI9STA ;;
  FabioAkita) ytfzf -D -c youtube-channel https://youtube.com/channel/UCib793mnUOhWymCh2VJKplQ ;;
  LinusTechTips) ytfzf -D -c youtube-channel https://youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw ;;
  PeperaioHardware) ytfzf -D -c youtube-channel https://youtube.com/channel/UCyJfHnEgLnvrjQcPsR3UVeQ ;;
  EiNerd) ytfzf -D -c youtube-channel https://youtube.com/channel/UCt_4wzTQqmcUvemNkeO0plA ;;
  Canal90) ytfzf -D -c youtube-channel https://youtube.com/channel/UCAmiE11hyW3iPdtQ9clqvtg ;;
  DioLinux) ytfzf -D -c youtube-channel https://youtube.com/channel/UCEf5U1dB5a2e2S-XUlnhxSA ;;
  DistroTube) ytfzf -D -c youtube-channel https://youtube.com/channel/UCVls1GmFKf6WlTraIb_IaJg ;;
  CovildeJack) ytfzf -D -c youtube-channel youtube.com/c/13thDeadJack ;;
  ResumindoFilmes) ytfzf -D -c youtube-channel https://youtube.com/channel/UCtFL4emnfs3GZw_INeQNjmg ;;
  ShortCircuit) ytfzf -D -c youtube-channel youtube.com/c/https://youtube.com/channel/UCdBK94H6oZT2Q7l0-b0xmMg ;;
  ThePrimeagen) ytfzf -D -c youtube-channel https://youtube.com/channel/UC8ENHE5xdFSwx71u3fDH5Xw ;;
  
esac
